version: "3"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      main:
        aliases:
          - redis

  gocoop:
    image: fallais/gocoop
    container_name: gocoop
    restart: always
    volumes:
      - /data/docker/config.yml:/usr/bin/config.yml
      - /sys:/sys
    command: --config_file /usr/bin/config.yml
    environment:
      - TZ=Europe/Paris
    networks:
      main:
        aliases:
          - gocoop

  goccop-frontend:
    image: fallais/gocoop-frontend
    container_name: gocoop-frontend
    restart: always
    networks:
      main:
        aliases:
          - gocoop-frontend

  caddy:
    image: elswork/arm-caddy
    container_name: caddy
    restart: always
    volumes:
      - /data/docker/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      main:
        aliases:
          - caddy

networks:
  main:
    driver: bridge
