latitude: 42.525776
longitude: 2.327727
gui_username: admin
gui_password: admin
redis_host: localhost:6379
redis_password: 
static_dir: web\dist\gocoop
opening:
  mode: "time_based"
  value: "08h00"
closing:
  mode: "sun_based"
  value: "-30m"