name: buildx

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --tag docker.io/fallais/gocoop \
            --output "type=image,push=false" \
            --file ./build/docker/Dockerfile . && \
          docker images
      
      - name: Publish to Registry
        run: |
          docker images && \
          docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }} && \
          docker push docker.io/fallais/gocoop