name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: /home/runner/work/fallais/go/src

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/fallais/go

      - name: Get dependencies
        run: go get -v -t -d ./...
        env:
          GOPATH: /home/runner/work/fallais/go
      
      - name: Test
        run: go test -cover ./...
        env:
          GOPATH: /home/runner/work/fallais/go

      - name: Build
        run: go build -v .
        env:
          GOPATH: /home/runner/work/fallais/go
      
      - name: Build the Docker image
        run: docker build -t gocoop -f build/docker/backend.Dockerfile .
